### PR TITLE
GRPH-46-AddQuitCommandToCliWallet - Add Quit command to CLI Wallet

### PR DESCRIPTION
**Pull request by gladcow**
Add `quit` command to the CLI Wallet.
Required for https://github.com/peerplays-network/peerplays/pull/90.
Backport of the Bitshares https://github.com/bitshares/bitshares-fc/pull/63

### CODE REVIEW

**Review by pbattu123 — APPROVED** [review]
Looks good to me.

**Comment by oxarbitrage** [comment]
There were some additional problems with this command in bitshares iirc. 
Check for example: https://github.com/bitshares/bitshares-fc/blob/master/src/rpc/cli.cpp#L114
I will make some tests but i think something could be missing for the command to work properly.

**Comment by gladcow** [comment]
@oxarbitrage , Bitshares has much more complex CLI than Peerplays,  that's why it has more complex exit procedure. In particular,  the code you are talking about is added in https://github.com/bitshares/bitshares-core/pull/1695,  that is not backported by the Peerplays. We should add this code after we adopt additional CLI features from Bitshares (complex command completion and command history). I've tested the current implementation and haven't reproduced any issues with CLI wallet exit.

**Comment by oxarbitrage** [comment]
ok, that makes sense. thanks. lets do it then.

**Review by oxarbitrage — APPROVED** [review]

**Pull request merged**
